### ISSUE TITLE
多文件如何上传

### ISSUE THREAD

**Issue by lepig** [Tinywan/webman-storage#20]
单文件通过`$res = Storage::uploadFile();`可以正常上传到阿里云oss

那么我在postman里选择了2个文件，然后提交后只能成功一个。 请问一下如何设置呢？

**Comment by lepig** [comment]
我将postman里的file字段修改为file[]，后端提示
`Error: Call to a member function isValid() on array in
/home/vagrant/code/webman/vendor/tinywan/storage/src/Adapter/AdapterAbstract.php:149<br />`

**Comment by Tinywan** [comment]
这个是循环上传的，怎么会只有一个来

![image](https://github.com/user-attachments/assets/0c85cbaf-91cd-4701-a378-60146d11a5ee)

**Comment by lepig** [comment]
![1](https://github.com/user-attachments/assets/fc3bd28c-260a-4cb1-b5ff-b4eb2f366934)
![2](https://github.com/user-attachments/assets/d844042d-12e0-4589-ae0c-6931d616708d)

昨天是这样操作的，主要是postman里的KEY我是使用了file，然后也测试了file[]都出问题，
后来今天上午我来改成了你截图的这种。 传2个不同的key就行了。

**Comment by Tinywan** [comment]
那问题不就解决了
