### ISSUE TITLE
七牛的适配器有bug

### ISSUE THREAD

**Issue by Bigweixi** [Tinywan/webman-storage#7]
文档中
// 第二个参数要设置为 `false`
Tinywan\Storage\Storage::config(Storage::MODE_OSS, false);

七牛如果设置为 false    抽象类的 loadConfig 就没有执行  驱动器内部 this->config  就为null 
 loadConfig  是保护的 无法直接调用  

Storage::config(Storage::MODE_OSS, false); 参数2 设置成true 的话  
   public function getUploadToken(): string
    {
        if ($this->uploadToken) {
            $auth = new Auth($this->config['accessKey'], $this->config['secretKey']);
            $this->uploadToken = $auth->uploadToken($this->config['bucket']);
        }

        return $this->uploadToken;
    }

发现    if ($this->uploadToken) {    这句反了
没提交过pr  我就加个 issue 吧

**Comment by Tinywan** [comment]
感谢反馈！[v0.3.3](https://github.com/Tinywan/webman-storage/releases/tag/v0.3.3) 已修复
