### ISSUE TITLE
上传文件数量过多，超出系统文件数量限制

### ISSUE THREAD

**Issue by wang-junda** [Tinywan/webman-storage#9]
![image](https://user-images.githubusercontent.com/50827006/174935883-baf9d502-d1f1-4ff0-9ecd-b1d2c070b872.png)

这个是扩展默认配置
![image](https://user-images.githubusercontent.com/50827006/174935980-0265145f-1809-40fd-97b2-3b8ba803fe31.png)

默认调用示例
![image](https://user-images.githubusercontent.com/50827006/174936033-ecbebcdf-2c08-452d-8d4e-3671f38be7a2.png)

**Comment by Tinywan** [comment]
修改文件上传参数就可以啦

**Comment by wang-junda** [comment]
就上传一个文件，也是报这个，我重新拉个框架安装试试

**Comment by Tinywan** [comment]
没有遇到过哎
